server:
  port: ${SERVER_PORT}

management:
  endpoints:
      web:
        exposure:
          include: info,health
spring:
  application:
    name: '@name@'

x-aerospike:
  host: ${DB_HOST}
  port: ${DB_PORT}
  namespace: ${DB_NAMESPACE}