server:
  port: ${SERVER_PORT}

spring:
  application:
    name: '@name@'

x-aerospike:
  host: ${DB_HOST}
  port: ${DB_PORT}
  namespace: ${DB_NAMESPACE}

logging:
  level:
    org:
      springframework:
        web: ${LOG_LEVEL}
        data:
          aerospike: ${LOG_LEVEL}